from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from pptx import Presentation
from pptx.util import Inches as PptxInches, Pt as PptxPt
from io import BytesIO
import re

class DocGenService:
    def __init__(self):
        pass

    def _clean_markdown(self, text: str) -> str:
        """
        Removes Markdown formatting for professional document output.
        - Removes **bold** markers
        - Removes ## Headings markers
        - Cleans up bullet points for DOCX (PPTX handles them separately)
        """
        if not text:
            return ""
        
        # Remove bold/italic markers (** or *)
        text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)  # Bold
        text = re.sub(r'\*(.*?)\*', r'\1', text)      # Italic
        
        # Remove Heading markers (### Title)
        text = re.sub(r'^#+\s*', '', text, flags=re.MULTILINE)
        
        return text.strip()

    def create_docx(self, project_title: str, sections: list) -> BytesIO:
        """Create a Word document from project data"""
        doc = Document()
        
        # Add title
        title = doc.add_heading(project_title, 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Add sections
        for section in sections:
            # Add section heading (Level 1)
            doc.add_heading(section["title"], 1)
            
            content = section.get("content")
            if content:
                # Clean the content before adding
                clean_content = self._clean_markdown(content)
                
                # Split by newlines to preserve paragraphs
                paragraphs = clean_content.split('\n')
                for p_text in paragraphs:
                    if p_text.strip():
                        # Check if it looks like a list item
                        if p_text.strip().startswith(('-', '•', '*')):
                            # Add as a list item style
                            p = doc.add_paragraph(p_text.strip().lstrip('-•* '), style='List Bullet')
                        else:
                            # Regular paragraph
                            doc.add_paragraph(p_text)
            else:
                doc.add_paragraph("[No content generated yet]", style='Intense Quote')
            
            # Add spacing
            doc.add_paragraph()
        
        # Save to BytesIO
        file_stream = BytesIO()
        doc.save(file_stream)
        file_stream.seek(0)
        
        return file_stream

    def create_pptx(self, project_title: str, sections: list) -> BytesIO:
        """Create a PowerPoint presentation from project data"""
        prs = Presentation()
        
        # Set slide width and height (16:9)
        prs.slide_width = PptxInches(10)
        prs.slide_height = PptxInches(7.5)
        
        # Title slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        
        title.text = project_title
        subtitle.text = "Generated by NexWrit"
        
        # Add content slides
        for section in sections:
            # Use title and content layout
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            
            # Set title
            title_shape = slide.shapes.title
            title_shape.text = section["title"]
            
            # Set content
            content_shape = slide.placeholders[1]
            text_frame = content_shape.text_frame
            text_frame.clear()
            
            if section.get("content"):
                # Clean markdown first
                content = self._clean_markdown(section["content"])
                
                # Parse content into bullet points
                lines = content.split('\n')
                for line in lines:
                    line = line.strip()
                    if line:
                        # Remove existing bullet markers if present to avoid double bullets
                        if line.startswith(('•', '-', '*')):
                            line = line.lstrip('•-* ').strip()
                        
                        p = text_frame.add_paragraph()
                        p.text = line
                        p.level = 0
            else:
                p = text_frame.add_paragraph()
                p.text = "[No content generated yet]"
        
        # Save to BytesIO
        file_stream = BytesIO()
        prs.save(file_stream)
        file_stream.seek(0)
        
        return file_stream

# Global instance
doc_gen_service = DocGenService()